const RouteName = {
  AUTH_NAVIGATION: 'AUTH_NAVIGATION',
  APP_NAVIGATION: 'APP_NAVIGATION',
  DRAWER_NAVIGATION: 'DRAWER_NAVIGATION',
  DASHBOARD_SCREEN: 'DASHBOARD_SCREEN',
  INDEX_SCREEN: 'INDEX_SCREEN',
} as const;
export default RouteName;
