const RouteName = {
  AUTH_NAVIGATION: 'AUTH_NAVIGATION',
  APP_NAVIGATION: 'APP_NAVIGATION',
  DRAWER_NAVIGATION: 'DRAWER_NAVIGATION',
  DASHBOARD_SCREEN: 'DASHBOARD_SCREEN',
  INDEX_SCREEN: 'INDEX_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  OTP_VERIFICATION_SCREEN: 'OTP_VERIFICATION_SCREEN',
  USERDETAILS_FILL_SCREEN: 'USERDETAILS_FILL_SCREEN',
} as const;
export default RouteName;
